// Copyright (c) 2026 Opensense Ltd. (Hong Kong). All rights reserved.
// Proprietary software. No use, copy, modification, distribution, disclosure,
// or reverse engineering is permitted without prior written authorization
// from Opensense Ltd.

package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"sort"
	"strings"
)

type policyAPIWriteRequest struct {
	ID                         string   `json:"id"`
	Name                       string   `json:"name"`
	Capabilities               []string `json:"capabilities"`
	ReviewRequiredCapabilities []string `json:"review_required_capabilities"`
}

type policyAPIApplyRequest struct {
	Workspace string `json:"workspace"`
}

func (a *App) handleUserPoliciesAPI(w http.ResponseWriter, r *http.Request) {
	user := a.requireUserBackendAPIUser(w, r)
	if user == nil {
		return
	}
	if r.URL.Path != "/api/user/policies" {
		writeError(w, http.StatusNotFound, "not_found", "policy endpoint not found")
		return
	}
	switch r.Method {
	case http.MethodGet:
		a.writePolicyAPIList(w, user.ID)
	case http.MethodPost:
		a.handleUserPolicyAPICreate(w, r, user)
	default:
		writeError(w, http.StatusMethodNotAllowed, "method_not_allowed", "GET or POST required")
	}
}

func (a *App) handleUserPolicyAPI(w http.ResponseWriter, r *http.Request) {
	user := a.requireUserBackendAPIUser(w, r)
	if user == nil {
		return
	}
	policyID, action, ok := parsePolicyAPIPath(r.URL.Path)
	if !ok {
		writeError(w, http.StatusNotFound, "not_found", "policy endpoint not found")
		return
	}
	if action == "apply" {
		if r.Method != http.MethodPost {
			writeError(w, http.StatusMethodNotAllowed, "method_not_allowed", "POST required")
			return
		}
		a.handleUserPolicyAPIApply(w, r, user, policyID)
		return
	}
	switch r.Method {
	case http.MethodGet:
		a.writePolicyAPIDetail(w, user.ID, policyID)
	case http.MethodPut, http.MethodPatch:
		a.handleUserPolicyAPIUpdate(w, r, user, policyID)
	case http.MethodDelete:
		a.handleUserPolicyAPIDelete(w, r, user, policyID)
	default:
		writeError(w, http.StatusMethodNotAllowed, "method_not_allowed", "GET, PUT, PATCH, or DELETE required")
	}
}

func parsePolicyAPIPath(path string) (policyID, action string, ok bool) {
	tail := strings.Trim(strings.TrimPrefix(path, "/api/user/policies/"), "/")
	if tail == "" || tail == path {
		return "", "", false
	}
	parts := strings.Split(tail, "/")
	if len(parts) > 2 {
		return "", "", false
	}
	rawID, err := url.PathUnescape(parts[0])
	if err != nil || strings.TrimSpace(rawID) == "" {
		return "", "", false
	}
	if len(parts) == 2 {
		if parts[1] != "apply" {
			return "", "", false
		}
		action = "apply"
	}
	return strings.TrimSpace(rawID), action, true
}

func (a *App) handleUserPolicyAPICreate(w http.ResponseWriter, r *http.Request, user *User) {
	var req policyAPIWriteRequest
	if !a.decodePolicyAPIJSON(w, r, &req, true) {
		return
	}
	switch strings.TrimSpace(req.ID) {
	case systemPolicyID:
		writeError(w, http.StatusBadRequest, "system_policy_immutable", "system default policy cannot be created")
		return
	case "":
	default:
		writeError(w, http.StatusBadRequest, "policy_id_not_allowed", "policy ID is generated by the server")
		return
	}
	policy, ok := a.policyFromAPIRequest(w, user.ID, "", req)
	if !ok {
		return
	}
	if err := a.store.SaveUserPolicy(policy); err != nil {
		writePolicyAPIStoreError(w, err)
		return
	}
	a.logPolicyAudit(r, user, "", "policy_created", policy.ID, policy.Name, map[string]any{"capabilities": policy.EnabledCapabilities, "review_required_capabilities": policy.ReviewRequiredCapabilities, "source": "api"})
	writeJSON(w, http.StatusCreated, map[string]any{"policy": a.policyAPIViewByID(user.ID, policy.ID)})
}

func (a *App) handleUserPolicyAPIUpdate(w http.ResponseWriter, r *http.Request, user *User, policyID string) {
	if policyID == systemPolicyID {
		writeError(w, http.StatusBadRequest, "system_policy_immutable", "system default policy cannot be updated")
		return
	}
	var req policyAPIWriteRequest
	if !a.decodePolicyAPIJSON(w, r, &req, true) {
		return
	}
	if bodyID := strings.TrimSpace(req.ID); bodyID != "" && bodyID != policyID {
		writeError(w, http.StatusBadRequest, "policy_id_mismatch", "body policy ID must match the URL policy ID")
		return
	}
	if existing, err := a.store.GetUserPolicy(user.ID, policyID); err != nil {
		writeError(w, http.StatusInternalServerError, "db_error", err.Error())
		return
	} else if existing == nil {
		writeError(w, http.StatusNotFound, "policy_not_found", "policy not found")
		return
	}
	policy, ok := a.policyFromAPIRequest(w, user.ID, policyID, req)
	if !ok {
		return
	}
	if err := a.store.SaveUserPolicy(policy); err != nil {
		writePolicyAPIStoreError(w, err)
		return
	}
	agentIDs, _ := a.store.AgentIDsForPolicy(user.ID, policy.ID)
	_ = a.store.MarkAgentsSkillStale(user.ID, agentIDs, "Policy \""+policy.Name+"\" changed.")
	a.logPolicyAudit(r, user, "", "policy_updated", policy.ID, policy.Name, map[string]any{"capabilities": policy.EnabledCapabilities, "review_required_capabilities": policy.ReviewRequiredCapabilities, "source": "api"})
	writeJSON(w, http.StatusOK, map[string]any{"policy": a.policyAPIViewByID(user.ID, policy.ID)})
}

func (a *App) handleUserPolicyAPIDelete(w http.ResponseWriter, r *http.Request, user *User, policyID string) {
	if policyID == systemPolicyID {
		writeError(w, http.StatusBadRequest, "system_policy_immutable", "system default policy cannot be deleted")
		return
	}
	policy, _ := a.store.GetUserPolicy(user.ID, policyID)
	agentIDs, _ := a.store.AgentIDsForPolicy(user.ID, policyID)
	targetName := policyID
	if policy != nil {
		targetName = policy.Name
	}
	reverted, err := a.store.DeleteUserPolicy(user.ID, policyID)
	if err != nil {
		writePolicyAPIStoreError(w, err)
		return
	}
	_ = a.store.MarkAgentsSkillStale(user.ID, agentIDs, "A policy used by this agent was deleted.")
	a.logPolicyAudit(r, user, "", "policy_deleted", policyID, targetName, map[string]any{"reverted": reverted, "source": "api"})
	writeJSON(w, http.StatusOK, map[string]any{
		"deleted_policy_id": policyID,
		"reverted_to":       systemPolicyID,
		"reverted_applied":  reverted,
	})
}

func (a *App) handleUserPolicyAPIApply(w http.ResponseWriter, r *http.Request, user *User, policyID string) {
	var req policyAPIApplyRequest
	if !a.decodePolicyAPIJSON(w, r, &req, false) {
		return
	}
	if err := a.ensurePolicyCanBeApplied(user.ID, policyID); err != nil {
		writePolicyAPIStoreError(w, err)
		return
	}
	workspace := strings.TrimSpace(req.Workspace)
	if workspace != "" {
		writeError(w, http.StatusBadRequest, "workspace_policy_deprecated", "workspace policies are configured per agent grant")
		return
	}
	if err := a.store.SaveDefaultPolicyID(user.ID, policyID); err != nil {
		writePolicyAPIStoreError(w, err)
		return
	}
	a.logPolicyAudit(r, user, "", "default_policy_changed", policyID, a.policyDisplayNameForUser(user.ID, policyID), map[string]any{"source": "api"})
	writeJSON(w, http.StatusOK, map[string]any{
		"applied_as": "default",
		"policy":     a.policyAPIViewByID(user.ID, policyID),
	})
}

func (a *App) writePolicyAPIList(w http.ResponseWriter, userID string) {
	policies, err := a.store.ListUserPolicies(userID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "db_error", err.Error())
		return
	}
	items := []map[string]any{a.systemPolicyAPIView(userID)}
	for i := range policies {
		items = append(items, a.policyAPIView(userID, &policies[i]))
	}
	writeJSON(w, http.StatusOK, map[string]any{"policies": items})
}

func (a *App) writePolicyAPIDetail(w http.ResponseWriter, userID, policyID string) {
	if policyID == systemPolicyID {
		writeJSON(w, http.StatusOK, map[string]any{"policy": a.systemPolicyAPIView(userID)})
		return
	}
	policy, err := a.store.GetUserPolicy(userID, policyID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "db_error", err.Error())
		return
	}
	if policy == nil {
		writeError(w, http.StatusNotFound, "policy_not_found", "policy not found")
		return
	}
	writeJSON(w, http.StatusOK, map[string]any{"policy": a.policyAPIView(userID, policy)})
}

func (a *App) policyFromAPIRequest(w http.ResponseWriter, userID, policyID string, req policyAPIWriteRequest) (*UserPolicy, bool) {
	name := strings.TrimSpace(req.Name)
	if name == "" {
		writeError(w, http.StatusBadRequest, "policy_name_required", "policy name cannot be empty")
		return nil, false
	}
	capabilities, err := normalizePolicyAPICapabilities(req.Capabilities)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_capability", err.Error())
		return nil, false
	}
	reviewRequired, err := normalizePolicyAPICapabilities(req.ReviewRequiredCapabilities)
	if err != nil {
		writeError(w, http.StatusBadRequest, "invalid_review_required_capability", err.Error())
		return nil, false
	}
	enabled := sliceToSet(capabilities)
	filteredReviewRequired := make([]string, 0, len(reviewRequired))
	for _, key := range reviewRequired {
		if !enabled[key] {
			writeError(w, http.StatusBadRequest, "invalid_review_required_capability", fmt.Sprintf("review-required capability %q must also be enabled", key))
			return nil, false
		}
		filteredReviewRequired = append(filteredReviewRequired, key)
	}
	return &UserPolicy{
		ID:                         policyID,
		UserID:                     userID,
		Name:                       name,
		EnabledCapabilities:        capabilities,
		ReviewRequiredCapabilities: filteredReviewRequired,
	}, true
}

func normalizePolicyAPICapabilities(keys []string) ([]string, error) {
	valid := map[string]bool{}
	for _, cap := range PolicyCatalog() {
		valid[cap.Key] = true
	}
	seen := map[string]bool{}
	out := []string{}
	for _, raw := range keys {
		key := strings.TrimSpace(raw)
		if key == "" {
			return nil, fmt.Errorf("capability key cannot be empty")
		}
		if !valid[key] {
			return nil, fmt.Errorf("unknown capability key %q", key)
		}
		if seen[key] {
			continue
		}
		seen[key] = true
		out = append(out, key)
	}
	sort.Strings(out)
	return out, nil
}

func (a *App) ensurePolicyCanBeApplied(userID, policyID string) error {
	policyID = strings.TrimSpace(policyID)
	if policyID == "" {
		return fmt.Errorf("policy not found")
	}
	if policyID == systemPolicyID {
		return nil
	}
	policy, err := a.store.GetUserPolicy(userID, policyID)
	if err != nil {
		return err
	}
	if policy == nil {
		return fmt.Errorf("policy not found")
	}
	return nil
}

func (a *App) decodePolicyAPIJSON(w http.ResponseWriter, r *http.Request, dst any, requireBody bool) bool {
	body, err := readBodyLimited(r, a.cfg.MaxRequestBodyBytes)
	if err != nil {
		writeError(w, http.StatusRequestEntityTooLarge, "request_too_large", err.Error())
		return false
	}
	if len(strings.TrimSpace(string(body))) == 0 {
		if requireBody {
			writeError(w, http.StatusBadRequest, "json_required", "JSON request body is required")
			return false
		}
		return true
	}
	if err := json.Unmarshal(body, dst); err != nil {
		writeError(w, http.StatusBadRequest, "invalid_json", err.Error())
		return false
	}
	return true
}

func (a *App) policyAPIViewByID(userID, policyID string) map[string]any {
	if policyID == systemPolicyID {
		return a.systemPolicyAPIView(userID)
	}
	policy, err := a.store.GetUserPolicy(userID, policyID)
	if err != nil || policy == nil {
		return map[string]any{"id": policyID}
	}
	return a.policyAPIView(userID, policy)
}

func (a *App) systemPolicyAPIView(userID string) map[string]any {
	settings, _ := a.store.GetUserSettings(userID)
	return map[string]any{
		"id":                           systemPolicyID,
		"name":                         systemPolicyName,
		"capabilities":                 SystemDefaultCapabilityKeys(),
		"review_required_capabilities": []string{},
		"system":                       true,
		"immutable":                    true,
		"is_default":                   settings.DefaultPolicyID == "" || settings.DefaultPolicyID == systemPolicyID,
	}
}

func (a *App) policyAPIView(userID string, policy *UserPolicy) map[string]any {
	settings, _ := a.store.GetUserSettings(userID)
	return map[string]any{
		"id":                           policy.ID,
		"name":                         policy.Name,
		"capabilities":                 policy.EnabledCapabilities,
		"review_required_capabilities": policy.ReviewRequiredCapabilities,
		"system":                       false,
		"immutable":                    false,
		"is_default":                   settings.DefaultPolicyID == policy.ID,
		"created_at":                   policy.CreatedAt,
		"updated_at":                   policy.UpdatedAt,
	}
}

func writePolicyAPIStoreError(w http.ResponseWriter, err error) {
	msg := err.Error()
	status := http.StatusBadRequest
	code := "policy_error"
	switch {
	case strings.Contains(msg, "not found"):
		status = http.StatusNotFound
		code = "not_found"
	case strings.Contains(msg, "system default policy"):
		code = "system_policy_immutable"
	case strings.Contains(msg, "UNIQUE constraint failed"):
		code = "duplicate_policy_name"
		msg = "policy name already exists"
	default:
		code = "invalid_policy"
	}
	writeError(w, status, code, msg)
}
